version: '3.8'

services:
  web:
    image: ifob_scool:latest
    container_name: ifob_scool
    ports:
      - "5002:80"
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    labels:
      - "com.ifob_scool.description=IFOB School Landing Page"
